application:
  auth-provider: mock
  services:
    authorization:
      url: ${AUTHORIZATION_SERVER_URL:http://localhost:9999}
    profile:
      url: ${PROFILE_SERVER_URL:http://localhost:8090}
    event:
      url: ${EVENT_SERVER_URL:http://localhost:8070}
    image-storage:
      url: ${IMAGE_STORAGE_SERVER_URL:http://localhost:8050}
server:
  port: 8080

spring:
  application:
    name: gateway
