version: '3.8'
services:
  postgresql:
    container_name: go_db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: go
      POSTGRES_PASSWORD: gogogo
      POSTGRES_DB: go
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d